version: '3.8'

services:
  crypto-news-bot:
    build: .
    container_name: crypto-news-bot
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./instance:/app/instance 